# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_remove_employee_roles_employee_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrscanlog',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='qrscanlog',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='qrscanlog',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
