# Generated by Django 6.0.4 on 2026-06-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_qrscanlog_device_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrscanlog',
            name='failure_reason',
        ),
        migrations.RemoveField(
            model_name='qrscanlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='qrscanlog',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='attendance',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
