# Generated by Django 6.0.4 on 2026-06-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_remove_qrscanlog_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrscanlog',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='qrscanlog',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='qrscanlog',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
