# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_qrscanlog_failure_reason_qrscanlog_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_pin',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='signature_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
