# Generated by Django 6.0.6 on 2026-06-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_employee_attendance_pin_signature_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type')},
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='last_updated',
        ),
    ]
