# Generated by Django 6.0.6 on 2026-06-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_employee_attendance_pin_signature_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='signature_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
