# Generated by Django 6.0.6 on 2026-06-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_leavebalance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
    ]
