# Generated by Django 6.0.6 on 2026-06-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_leaverequest_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
    ]
