# Generated by Django 6.0.6 on 2026-07-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_alter_leaverequest_status'),
        ('hr', '0013_supervisor_cert_holiday_payrollrecord_kpiscore'),
    ]

    operations = [
    ]
