# Generated by Django 6.0.6 on 2026-07-08 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_merge_20260708_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='attachment',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='contact_info_during_leave',
            field=models.CharField(blank=True, default='', help_text='Phone number or address where employee can be reached during leave', max_length=255),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='supervisor_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='supervisor_recommendation',
            field=models.CharField(blank=True, choices=[('', 'Pending Supervisor Review'), ('recommended', 'Recommended'), ('not_recommended', 'Not Recommended')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='supervisor_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_leave_reviews', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='supervisor_reviewed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Recommended', 'Recommended'), ('Not Recommended', 'Not Recommended'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('HR Approved', 'HR Approved'), ('Paid', 'Paid'), ('On Hold', 'On Hold')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='performanceevaluation',
            name='outcome',
            field=models.CharField(blank=True, choices=[('passed_probation', 'Passed Probation -> now permanent'), ('failed_probation', 'Failed Probation'), ('promoted', 'Promoted'), ('salary_raise', 'Salary Raise Approved'), ('warning', 'Warning Issued'), ('no_change', 'No Change')], max_length=20, null=True),
        ),
    ]
