# Generated by Django 5.2.8 on 2026-07-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_leave_supervisor_contact_payroll_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('position_title', models.CharField(max_length=100)),
                ('number_needed', models.PositiveIntegerField(default=1)),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Temporary', 'Temporary')], default='Full-Time', max_length=50)),
                ('reason', models.TextField()),
                ('required_skills', models.TextField(blank=True, default='')),
                ('preferred_start_date', models.DateField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('hr_comment', models.TextField(blank=True, default='')),
                ('created_vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_requests', to='hr.jobposting')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_requests', to='hr.department')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_requests', to='hr.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_hiring_requests', to='hr.employee')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
    ]
