# Generated by Django 6.0.6 on 2026-07-22 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_leavebalance_last_updated_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='leavebalance',
                    name='last_updated',
                    field=models.DateField(auto_now=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='biannualkpiscore',
            name='evaluation_type',
            field=models.CharField(choices=[('self', 'Self'), ('peer', 'Peer'), ('supervisor', 'Supervisor'), ('hr', 'HR')], max_length=20),
        ),
        migrations.CreateModel(
            name='DisciplinaryIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('incident_date', models.DateField()),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('evidence_attachment', models.FileField(blank=True, null=True, upload_to='discipline_evidence/')),
                ('employee_response', models.TextField(blank=True, default='')),
                ('offense_number', models.CharField(blank=True, default='', max_length=50)),
                ('investigation_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Reported', 'Reported'), ('Under Investigation', 'Under Investigation'), ('Decision', 'Decision'), ('Employee Acknowledgment', 'Employee Acknowledgment'), ('Appeal', 'Appeal'), ('Closed', 'Closed')], default='Reported', max_length=40)),
                ('action_taken', models.CharField(choices=[('No Action', 'No Action'), ('Verbal Warning', 'Verbal Warning'), ('Written Warning', 'Written Warning'), ('Final Warning', 'Final Warning'), ('Suspension', 'Suspension'), ('Demotion', 'Demotion'), ('Dismissal', 'Dismissal')], default='No Action', max_length=40)),
                ('decision_reason', models.TextField(blank=True, default='')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_incidents', to='hr.employee')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_incidents', to='hr.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_incidents', to='hr.employee')),
                ('reporting_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to='hr.employee')),
            ],
            options={
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_reason', models.TextField()),
                ('appeal_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Submitted', max_length=20)),
                ('decision_comment', models.TextField(blank=True, default='')),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_appeals', to='hr.employee')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_reviews', to='hr.employee')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='hr.disciplinaryincident')),
            ],
            options={
                'ordering': ['-appeal_date'],
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='grievance_evidence/')),
                ('desired_resolution', models.TextField(blank=True, default='')),
                ('confidential', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Investigation', 'Investigation'), ('Action Required', 'Action Required'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Submitted', max_length=25)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('investigation_notes', models.TextField(blank=True, default='')),
                ('findings', models.TextField(blank=True, default='')),
                ('corrective_action', models.TextField(blank=True, default='')),
                ('response', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grievances', to='hr.employee')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to='hr.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to='hr.employee')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('In-House', 'In-House'), ('External', 'External'), ('Overseas', 'Overseas'), ('Online', 'Online')], default='In-House', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('funding_source', models.CharField(blank=True, default='', max_length=200)),
                ('business_justification', models.TextField(blank=True, default='')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='training_documents/')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Supervisor Review', 'Supervisor Review'), ('Supervisor Rejected', 'Supervisor Rejected'), ('HR Review', 'HR Review'), ('HR Rejected', 'HR Rejected'), ('Approved', 'Approved'), ('Completed', 'Completed')], default='Submitted', max_length=30)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('supervisor_comment', models.TextField(blank=True, default='')),
                ('supervisor_decision_date', models.DateTimeField(blank=True, null=True)),
                ('hr_comment', models.TextField(blank=True, default='')),
                ('hr_decision_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('cpd_points', models.PositiveIntegerField(default=0)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='training_certificates/')),
                ('skills_learned', models.TextField(blank=True, default='')),
                ('knowledge_transfer_method', models.CharField(blank=True, default='', max_length=200)),
                ('feedback', models.TextField(blank=True, default='')),
                ('satisfaction_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_requests', to='hr.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests', to='hr.employee')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_requests_reviewed', to='hr.employee')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
    ]
