# Generated by Django 6.0.6 on 2026-07-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_leavebalance_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='employees', to='hr.department', db_index=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='employees', to='hr.role', db_index=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=models.CASCADE, to='hr.employee', db_index=True),
        ),
    ]
