# Generated by Django 6.0.6 on 2026-07-22 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_leavebalance_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequest',
            name='request_source',
            field=models.CharField(choices=[('Employee', 'Employee Requested'), ('Supervisor', 'Supervisor Recommended')], default='Employee', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_requests_initiated', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='trainingrequest',
            name='required_skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
