# Generated by Django 6.0.6 on 2026-07-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_auto_20260722_0316'),
        ('hr', '0018_trainingrequest_request_source_and_more'),
    ]

    operations = [
    ]
