# Generated by Django 6.0.6 on 2026-08-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_employee_employment_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Screening', 'Screening'), ('Qualified', 'Qualified — passed auto screen'), ('Rejected_Auto', 'Rejected — auto screening'), ('Interviewed', 'Interviewed'), ('Selected', 'Selected'), ('Hired', 'Hired'), ('Rejected', 'Rejected — manual')], default='Applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='event_type',
            field=models.CharField(choices=[('hired', 'Employee Created'), ('recruitment_completed', 'Recruitment Completed'), ('onboarding_completed', 'Onboarding Completed'), ('probation_started', 'Probation Started'), ('probation_passed', 'Probation Completed'), ('probation_failed', 'Probation Failed'), ('promoted', 'Promotion'), ('transferred', 'Department Transfer'), ('position_change', 'Position Change'), ('salary_change', 'Salary Grade Change'), ('contract_renewed', 'Contract Renewed'), ('training_completed', 'Training Completed'), ('performance_review', 'Performance Review'), ('salary_raise', 'Salary Raise'), ('warned', 'Warning Issued'), ('suspended', 'Suspended'), ('reinstated', 'Reinstated'), ('terminated', 'Termination'), ('resigned', 'Resignation'), ('retired', 'Retirement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Recommended', 'Recommended'), ('Not Recommended', 'Not Recommended'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=20),
        ),
    ]
