# Generated by Django 6.0.6 on 2026-08-06 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_lifecycle_event_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeehistory',
            options={'ordering': ['-start_date', '-event_time']},
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_events_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='event_type',
            field=models.CharField(choices=[('application_submitted', 'Job Application Submitted'), ('application_reviewed', 'Application Reviewed'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('candidate_selected', 'Candidate Selected'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('hired', 'Employee Created'), ('recruitment_completed', 'Recruitment Completed'), ('onboarding_started', 'Onboarding Started'), ('onboarding_completed', 'Onboarding Completed'), ('probation_started', 'Probation Started'), ('probation_passed', 'Probation Completed'), ('confirmed_permanent', 'Confirmed as Permanent Employee'), ('probation_failed', 'Probation Failed'), ('promoted', 'Promotion'), ('demoted', 'Demotion'), ('transferred', 'Department Transfer'), ('position_change', 'Position Change'), ('salary_change', 'Salary Grade Change'), ('salary_raise', 'Salary Raise'), ('contract_renewed', 'Contract Renewed'), ('training_assigned', 'Training Assigned'), ('training_completed', 'Training Completed'), ('performance_review', 'Performance Review Completed'), ('warned', 'Warning Issued'), ('suspended', 'Suspended'), ('reinstated', 'Reinstated / Reactivated'), ('terminated', 'Termination'), ('resigned', 'Resignation'), ('retired', 'Retirement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_recorded', to='hr.employee'),
        ),
    ]
