from django.contrib import admin
from .models import *
# Register all models with the admin site
admin.site.register(SystemSetting)
admin.site.register(Department)
admin.site.register(Position)
admin.site.register(EmployeeStatus)
admin.site.register(Employee)
admin.site.register(Role)
admin.site.register(UserRole)
admin.site.register(JobPosting)
admin.site.register(JobVacancy)
admin.site.register(Applicant)
admin.site.register(Application)
admin.site.register(Interview)
admin.site.register(Attendance)
admin.site.register(QRScanLog)
admin.site.register(WorkSchedule)
admin.site.register(LeaveType)
admin.site.register(LeaveRequest)
admin.site.register(LeaveBalance)
admin.site.register(Salary)
admin.site.register(Payroll)
admin.site.register(KPICategory)
admin.site.register(KPIIndicator)
admin.site.register(PerformanceEvaluation)
admin.site.register(EvaluationScore)
admin.site.register(DisciplinaryRecord)
admin.site.register(EmployeeHistory)
admin.site.register(ExitRecord)
admin.site.register(RetirementBenefit)
admin.site.register(Notification)
admin.site.register(ChatbotSession)
admin.site.register(ChatbotConversation)
admin.site.register(Report)
admin.site.register(AuditLog)
